### ISSUE TITLE
Umbrella header for module Storyly does not include header

### ISSUE THREAD

**Issue by joeboyscout04** [Netvent/storyly-ios#2]
We've integrated Storyly with our app using SPM, but it's producing a lot of warnings like this:

```
Umbrella header for module 'Storyly' does not include header 'ST_SDImageAssetManager.h'
```

Is this something we should be concerned about?  Or is there some way to silence these warnings? 
![Screen Shot 2022-02-08 at 10 45 24 AM](https://user-images.githubusercontent.com/1489809/152961124-2eddd5ff-bd83-4c4a-a2f4-b2a8c406aa5b.png)

Thanks a lot,

**Comment by levent-oral** [comment]
Hello @joeboyscout04 , 

[Storyly Mobile #145](https://github.com/Netvent/storyly-mobile/issues/145) issue is same with this one. Please follow-up in there. We're using that repository for issue tracking in Storyly. This repo is only for Swift Package Manager releases. 

Thanks!
